# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('meinberlin_offlineevents', '0003_verbose_name_title')]

    dependencies = [
        ('a4_candy_offlineevents', '0002_require_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineevent',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
    ]
