# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:14
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'liqd_product_offlineevents'
         WHERE app_label = 'meinberlin_offlineevents';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'meinberlin_offlineevents';
                 WHERE app_label = 'liqd_product_offlineevents';"""


class Migration(migrations.Migration):

    replaces = [('liqd_product_offlineevents', '0004_update_content_types')]

    dependencies = [
        ('a4_candy_offlineevents', '0003_verbose_name_title'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
