# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_offlineevents', '0006_update_content_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineevent',
            name='event_type',
            field=models.CharField(default='Veranstaltung', help_text='The content of this field is shown in the timeline. It should have no more than 30 characters e.g. Information event or 3rd public workshop.', max_length=30, verbose_name='Event type'),
            preserve_default=False,
        ),
    ]
