# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('liqd_product_partners', '0006_information_blank')]

    dependencies = [
        ('a4_candy_partners', '0005_partner_imprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Information about your municipality'),
        ),
    ]
