# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_partners', '0008_custom_shorten_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Short description of your municipality'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(default='Beteiligungsplattform', max_length=100),
        ),
    ]
