# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 11:20
from __future__ import unicode_literals

import adhocracy4.images.fields
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('liqd_product_partners', '0012_wording_fixes')]

    dependencies = [
        ('a4_candy_partners', '0011_kommune_word_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(help_text='The description will be displayed on the landing page. max. 400 characters', max_length=400, verbose_name='Short description of your organisation'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='imprint',
            field=ckeditor.fields.RichTextField(help_text='Please provide all the legally required information of your imprint. The imprint will be shown on a separate page.', verbose_name='Imprint'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='You can provide general information about your participation platform to your visitors. It’s also helpful to name a general person of contact for inquiries. The information will be shown on a separate page that can be reached via the main menu.', verbose_name='Information about your organisation'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=adhocracy4.images.fields.ConfiguredImageField('logo', blank=True, help_text='The Logo representing your organisation. The image must be square and it should be min. 200 pixels wide and 200 pixels tall. Allowed file formats are png, jpeg, gif. The file size should be max. 5 MB.', upload_to='partners/logos', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='slogan',
            field=models.CharField(blank=True, help_text='The slogan will be shown below the title of your platform on the landing page. The slogan can provide context or additional information to the title. max. 200 characters', max_length=200, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(default='Beteiligungsplattform', help_text='The title of your platform will be shown on the landing page. It should be clear to the users that this is your participation platform. max. 100 characters', max_length=100, verbose_name='Title of your platform'),
        ),
    ]
