# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 15:23
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_partners'
         WHERE app_label = 'liqd_product_partners';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'liqd_product_partners';
                 WHERE app_label = 'a4_candy_partners';"""


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_partners', '0012_wording_fixes'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
