# Generated by Django 2.2.8 on 2019-12-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderatorinvite',
            name='site',
            field=models.CharField(default='localhost', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantinvite',
            name='site',
            field=models.CharField(default='localhost', max_length=200),
            preserve_default=False,
        ),
    ]
