# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_projects', '0002_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moderatorinvite',
            table=None,
        ),
        migrations.AlterModelTable(
            name='participantinvite',
            table=None,
        ),
    ]
