# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 15:36
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_projects'
         WHERE app_label = 'liqd_product_projects';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'liqd_product_projects';
                 WHERE app_label = 'a4_candy_projects';"""


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_projects', '0003_rename_tables_to_default'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
