# Generated by Django 3.2.19 on 2023-07-13 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0038_verbose_name_created_modified"),
        ("a4_candy_projects", "0004_verbose_name_created_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="Modified"
                    ),
                ),
                ("active_participants", models.PositiveIntegerField()),
                ("comments", models.IntegerField()),
                ("ratings", models.IntegerField()),
                ("written_ideas", models.IntegerField()),
                ("poll_answers", models.IntegerField()),
                ("live_questions", models.IntegerField()),
                ("display", models.BooleanField(default=False)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a4projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
