# Generated by Django 4.2.16 on 2024-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_projects", "0006_initialize_insights"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectinsight",
            name="unregistered_participants",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
