# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0005_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homepage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='emptypage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='simplepage',
            table=None,
        ),
    ]
