# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0006_rename_tables_to_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='body_de',
        ),
    ]
