# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0008_homepage_body_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='subtitle',
            new_name='subtitle_de',
        ),
    ]
