# Generated by Django 2.2.22 on 2021-05-12 07:45

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0008_update_hero_field_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle_de',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_de',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hero title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=80, verbose_name='Hero title'),
        ),
    ]
