# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0009_rename_subtitle_to_subtititle_de'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=500, verbose_name='Subtitle'),
        ),
    ]
