# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0010_homepage_subtitle_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplepage',
            old_name='body',
            new_name='body_de',
        ),
    ]
