# Generated by Django 4.2.17 on 2024-12-12 12:35

import apps.cms.blocks
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_cms_pages", "0010_auto_20220614_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body_streamfield_de",
            field=wagtail.fields.StreamField(
                [
                    ("col_list_image_cta_block", 7),
                    ("background_cta_block", 10),
                    ("columns_cta", 14),
                    ("html", 15),
                    ("paragraph", 16),
                    ("news", 19),
                    ("use_cases", 24),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    1: ("wagtail.images.blocks.ImageBlock", [], {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "List and Image"},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "CTA with Background"},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "CTA Column"},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 11), ("columns", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {}),
                    17: ("wagtail.blocks.CharBlock", (), {}),
                    18: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_news.NewsIndexPage"]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 17), ("news_page", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCasePage"]},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: ("wagtail.blocks.URLBlock", (), {}),
                    23: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCaseIndexPage"]},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 17),
                                ("use_cases", 21),
                                ("demo_platform", 22),
                                ("use_case_page", 23),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_streamfield_en",
            field=wagtail.fields.StreamField(
                [
                    ("col_list_image_cta_block", 7),
                    ("background_cta_block", 10),
                    ("columns_cta", 14),
                    ("html", 15),
                    ("paragraph", 16),
                    ("news", 19),
                    ("use_cases", 24),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    1: ("wagtail.images.blocks.ImageBlock", [], {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "List and Image"},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "CTA with Background"},
                    ),
                    9: ("wagtail.blocks.ListBlock", (8,), {}),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "CTA Column"},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 11), ("columns", 13)]],
                        {},
                    ),
                    15: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    16: ("wagtail.blocks.RichTextBlock", (), {}),
                    17: ("wagtail.blocks.CharBlock", (), {}),
                    18: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_news.NewsIndexPage"]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 17), ("news_page", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCasePage"]},
                    ),
                    21: ("wagtail.blocks.ListBlock", (20,), {}),
                    22: ("wagtail.blocks.URLBlock", (), {}),
                    23: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCaseIndexPage"]},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 17),
                                ("use_cases", 21),
                                ("demo_platform", 22),
                                ("use_case_page", 23),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_de",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 16),
                    ("downloads", 18),
                    ("quote", 22),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "CTA Column"},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {}),
                    21: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 19),
                                ("image", 2),
                                ("quote", 20),
                                ("quote_author", 3),
                                ("link", 21),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_en",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 16),
                    ("downloads", 18),
                    ("quote", 22),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "CTA Column"},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {}),
                    21: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 19),
                                ("image", 2),
                                ("quote", 20),
                                ("quote_author", 3),
                                ("link", 21),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_ky",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 16),
                    ("downloads", 18),
                    ("quote", 22),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "CTA Column"},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {}),
                    21: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 19),
                                ("image", 2),
                                ("quote", 20),
                                ("quote_author", 3),
                                ("link", 21),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_nl",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 16),
                    ("downloads", 18),
                    ("quote", 22),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "CTA Column"},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {}),
                    21: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 19),
                                ("image", 2),
                                ("quote", 20),
                                ("quote_author", 3),
                                ("link", 21),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_ru",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 16),
                    ("downloads", 18),
                    ("quote", 22),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "CTA Column"},
                    ),
                    15: ("wagtail.blocks.ListBlock", (14,), {}),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    20: ("wagtail.blocks.TextBlock", (), {}),
                    21: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 19),
                                ("image", 2),
                                ("quote", 20),
                                ("quote_author", 3),
                                ("link", 21),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
