# Generated by Django 4.2.18 on 2025-03-18 15:45

import apps.cms.blocks
from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_cms_pages", "0011_alter_homepage_body_streamfield_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body_streamfield_de",
            field=wagtail.fields.StreamField(
                [
                    ("col_list_image_cta_block", 7),
                    ("background_cta_block", 11),
                    ("columns_cta", 15),
                    ("html", 16),
                    ("paragraph", 17),
                    ("news", 20),
                    ("use_cases", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    1: ("wagtail.images.blocks.ImageBlock", [], {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "List and Image"},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 2),
                                ("link", 3),
                                ("link_text", 4),
                                ("alignment", 8),
                            ]
                        ],
                        {"label": "CTA with Background"},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 2),
                                ("link", 3),
                                ("link_text", 4),
                                ("alignment", 8),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 12), ("columns", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    17: ("wagtail.blocks.RichTextBlock", (), {}),
                    18: ("wagtail.blocks.CharBlock", (), {}),
                    19: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_news.NewsIndexPage"]},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("news_page", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCasePage"]},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: ("wagtail.blocks.URLBlock", (), {}),
                    24: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCaseIndexPage"]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 18),
                                ("use_cases", 22),
                                ("demo_platform", 23),
                                ("use_case_page", 24),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body_streamfield_en",
            field=wagtail.fields.StreamField(
                [
                    ("col_list_image_cta_block", 7),
                    ("background_cta_block", 11),
                    ("columns_cta", 15),
                    ("html", 16),
                    ("paragraph", 17),
                    ("news", 20),
                    ("use_cases", 25),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    1: ("wagtail.images.blocks.ImageBlock", [], {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("body", 2), ("link", 3), ("link_text", 4)]],
                        {"label": "List and Image"},
                    ),
                    6: ("wagtail.blocks.ListBlock", (5,), {}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 2),
                                ("link", 3),
                                ("link_text", 4),
                                ("alignment", 8),
                            ]
                        ],
                        {"label": "CTA with Background"},
                    ),
                    10: ("wagtail.blocks.ListBlock", (9,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 0), ("columns", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 2),
                                ("link", 3),
                                ("link_text", 4),
                                ("alignment", 8),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    14: ("wagtail.blocks.ListBlock", (13,), {}),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 12), ("columns", 14)]],
                        {},
                    ),
                    16: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    17: ("wagtail.blocks.RichTextBlock", (), {}),
                    18: ("wagtail.blocks.CharBlock", (), {}),
                    19: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_news.NewsIndexPage"]},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 18), ("news_page", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCasePage"]},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: ("wagtail.blocks.URLBlock", (), {}),
                    24: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["a4_candy_cms_use_cases.UseCaseIndexPage"]},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 18),
                                ("use_cases", 22),
                                ("demo_platform", 23),
                                ("use_case_page", 24),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_de",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 17),
                    ("downloads", 19),
                    ("quote", 23),
                ],
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 6),
                                ("link", 3),
                                ("link_text", 7),
                                ("alignment", 14),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {}),
                    22: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 20),
                                ("image", 2),
                                ("quote", 21),
                                ("quote_author", 3),
                                ("link", 22),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_en",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 17),
                    ("downloads", 19),
                    ("quote", 23),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 6),
                                ("link", 3),
                                ("link_text", 7),
                                ("alignment", 14),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {}),
                    22: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 20),
                                ("image", 2),
                                ("quote", 21),
                                ("quote_author", 3),
                                ("link", 22),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_ky",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 17),
                    ("downloads", 19),
                    ("quote", 23),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 6),
                                ("link", 3),
                                ("link_text", 7),
                                ("alignment", 14),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {}),
                    22: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 20),
                                ("image", 2),
                                ("quote", 21),
                                ("quote_author", 3),
                                ("link", 22),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_nl",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 17),
                    ("downloads", 19),
                    ("quote", 23),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 6),
                                ("link", 3),
                                ("link_text", 7),
                                ("alignment", 14),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {}),
                    22: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 20),
                                ("image", 2),
                                ("quote", 21),
                                ("quote_author", 3),
                                ("link", 22),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="simplepage",
            name="body_streamfield_ru",
            field=wagtail.fields.StreamField(
                [
                    ("html", 0),
                    ("richtext", 1),
                    ("image", 2),
                    ("faq", 5),
                    ("image_cta", 8),
                    ("col_list_image_cta_block", 12),
                    ("columns_cta", 17),
                    ("downloads", 19),
                    ("quote", 23),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.AccordeonBlock,),
                        {},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("entries", 4)]],
                        {},
                    ),
                    6: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [(1, "One column"), (2, "Two columns")]},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("body", 6), ("link", 3), ("link_text", 7)]],
                        {"label": "List and Image"},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 9), ("columns", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (1, "One column"),
                                (2, "Two columns"),
                                (3, "Three columns"),
                            ]
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 6),
                                ("link", 3),
                                ("link_text", 7),
                                ("alignment", 14),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    16: ("wagtail.blocks.ListBlock", (15,), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("columns_count", 13), ("columns", 16)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (apps.cms.blocks.DownloadBlock,),
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 3), ("documents", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("turquoise", "turquoise"),
                                ("blue", "dark blue"),
                            ]
                        },
                    ),
                    21: ("wagtail.blocks.TextBlock", (), {}),
                    22: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("color", 20),
                                ("image", 2),
                                ("quote", 21),
                                ("quote_author", 3),
                                ("link", 22),
                                ("link_text", 7),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
