# Generated by Django 2.2.2 on 2019-07-17 12:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0012_simplepage_body_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_streamfield_de',
            field=wagtail.core.fields.StreamField([('col_image_text_block', wagtail.core.blocks.StructBlock([('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[(1, 'One column'), (2, 'Two columns')])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('call_to_action', wagtail.core.blocks.StreamBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], required=False))], label='CTA Img Column body')))])), ('columns_cta', wagtail.core.blocks.StructBlock([('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[(1, 'One column'), (2, 'Two columns'), (3, 'Three columns')])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], label='CTA Column body')))])), ('background_col_cta', wagtail.core.blocks.StructBlock([('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[(1, 'One column'), (2, 'Two columns')])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], label='CTA Background Column body')))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_streamfield_en',
            field=wagtail.core.fields.StreamField([('col_image_text_block', wagtail.core.blocks.StructBlock([('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[(1, 'One column'), (2, 'Two columns')])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('body', wagtail.core.blocks.RichTextBlock(required=False)), ('call_to_action', wagtail.core.blocks.StreamBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], required=False))], label='CTA Img Column body')))])), ('columns_cta', wagtail.core.blocks.StructBlock([('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[(1, 'One column'), (2, 'Two columns'), (3, 'Three columns')])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], label='CTA Column body')))])), ('background_col_cta', wagtail.core.blocks.StructBlock([('columns_count', wagtail.core.blocks.ChoiceBlock(choices=[(1, 'One column'), (2, 'Two columns')])), ('columns', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StreamBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], label='CTA Background Column body')))])), ('html', wagtail.core.blocks.RawHTMLBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock())], blank=True),
        ),
    ]
