# Generated by Django 2.2.3 on 2019-07-23 09:17

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0013_homepage_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='teaser_de',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='teaser_en',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
