# Generated by Django 2.2.3 on 2019-07-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_pages', '0015_homepage_form_page'),
        ('a4_candy_cms_pages', '0014_list_img_block'),
    ]

    operations = [
    ]
