# Generated by Django 4.2.18 on 2025-04-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_learning_nuggets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="learningnuggetpage",
            options={"ordering": ["order"], "verbose_name": "Learning Nugget Page"},
        ),
        migrations.AddField(
            model_name="learningnuggetpage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
