# Generated by Django 4.2.18 on 2025-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_learning_nuggets", "0002_alter_learningnuggetpage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningnuggetpage",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
