# Generated by Django 4.2.18 on 2025-04-24 14:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_learning_nuggets", "0003_learningnuggetpage_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningnuggetpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("learning_nugget", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a clear, concise title for this learning nugget (max 100 characters recommended)",
                            "max_length": 100,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Provide a comprehensive description of the learning nugget, including key takeaways and learning objectives",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload a representative image that visually captures the content (recommended size: 600x400px, 3:2 ratio)"
                        },
                    ),
                    3: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {
                            "help_text": "Upload an image that visually captures the content (recommended size: 600x400px, 3:2 ratio)"
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 130, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Please insert a short description of the video (character limit 500).",
                            "max_length": 500,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Please upload or choose a media file with any of the following extensions: MP4, WebM, MP3, WAV",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "ol",
                                "ul",
                                "link",
                                "document-link",
                            ],
                            "help_text": "You can add the video's transcript here (unlimited characters).",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 4),
                                ("description", 5),
                                ("media", 6),
                                ("transcript", 7),
                            ]
                        ],
                        {
                            "help_text": "Upload or select an instructional video to complement the written content (MP4 format recommended - 20mb)",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Upload related documents such as worksheets, guides, or additional resources (PDF format recommended)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 3), ("video", 8), ("document", 9)]],
                        {
                            "help_text": "Choose optional content: videos, images, or documents.",
                            "label": "Extras",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("description", 1),
                                ("thumbnail", 2),
                                ("extras", 10),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
