# Generated by Django 4.2.18 on 2025-05-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_learning_nuggets", "0004_alter_learningnuggetpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningcategory",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("participant", "Teilnehmer"),
                    ("initiator", "Initiator"),
                    ("moderator", "Moderator"),
                ],
                default="participant",
                max_length=50,
            ),
        ),
    ]
