# Generated by Django 4.2.18 on 2025-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_learning_nuggets", "0005_alter_learningcategory_permission_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningcategory",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("teilnehmer", "Teilnehmer"),
                    ("initiator", "Initiator"),
                    ("moderator", "Moderator"),
                ],
                default="teilnehmer",
                max_length=50,
            ),
        ),
    ]
