# Generated by Django 4.2.18 on 2025-05-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_learning_nuggets", "0006_alter_learningcategory_permission_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningcategory",
            name="permission_level",
            field=models.CharField(
                choices=[
                    ("teilnehmer:in", "Teilnehmer:in"),
                    ("initiator:in", "Initiator:in"),
                    ("moderator:in", "Moderator:in"),
                ],
                default="teilnehmer:in",
                max_length=50,
            ),
        ),
    ]
