# Generated by Django 2.2.3 on 2019-08-07 17:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subtitle_de', models.CharField(blank=True, max_length=250, verbose_name='Title')),
                ('subtitle_en', models.CharField(blank=True, max_length=250, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='UseCasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', models.CharField(choices=[('MP', 'Municipalities'), ('CA', 'Citizen Assemblies'), ('CN', 'Co-Operatives/NGOs'), ('CP', 'Companies'), ('PO', 'Politicians')], max_length=2)),
                ('demo_link', models.URLField(blank=True, verbose_name='Demo site')),
                ('title_de', models.CharField(blank=True, max_length=250, verbose_name='German Title')),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='English Title')),
                ('teaser_de', models.TextField(blank=True, null=True, verbose_name='Teaser Text')),
                ('teaser_en', models.TextField(blank=True, null=True, verbose_name='Teaser Text')),
                ('body_streamfield_de', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True)),
                ('body_streamfield_en', wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock())], blank=True)),
                ('image', models.ForeignKey(blank=True, help_text='The Image that is shown on the use case item page and the use case index page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Use Case Header Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
