# Generated by Django 2.2.6 on 2019-11-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasepage',
            name='category',
            field=models.CharField(choices=[('MP', 'Municipalities'), ('CA', 'Citizen Assemblies'), ('NG', 'Associations & NGOs'), ('CP', 'Companies & Co-Operatives'), ('PO', 'Politicians')], max_length=2),
        ),
    ]
