# Generated by Django 2.2.4 on 2019-08-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecaseindexpage',
            name='demo_link',
            field=models.URLField(blank=True, verbose_name='Demo site'),
        ),
    ]
