# Generated by Django 2.2.4 on 2019-08-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_contacts', '0003_add_contact_person_data'),
        ('a4_candy_cms_use_cases', '0002_usecaseindexpage_demo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecaseindexpage',
            name='form_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a4_candy_cms_contacts.FormPage'),
        ),
    ]
