# Generated by Django 2.2.4 on 2019-08-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0003_usecaseindexpage_form_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecasepage',
            name='demo_link',
        ),
        migrations.RemoveField(
            model_name='usecasepage',
            name='teaser_de',
        ),
        migrations.RemoveField(
            model_name='usecasepage',
            name='teaser_en',
        ),
    ]
