# Generated by Django 4.2.18 on 2025-03-18 15:45

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_cms_use_cases", "0003_auto_20220614_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usecasepage",
            name="body_streamfield_de",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("html", 1), ("examples", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 2),
                                ("link", 3),
                                ("link_text", 4),
                                ("alignment", 5),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("wagtail.blocks.StructBlock", [[("examples", 7)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="usecasepage",
            name="body_streamfield_en",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("html", 1), ("examples", 8)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.RawHTMLBlock", (), {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Link Text", "max_length": 50, "required": False},
                    ),
                    5: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("justify", "Justify"),
                            ],
                            "label": "Text Alignment",
                        },
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("body", 2),
                                ("link", 3),
                                ("link_text", 4),
                                ("alignment", 5),
                            ]
                        ],
                        {"label": "CTA Column"},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("wagtail.blocks.StructBlock", [[("examples", 7)]], {}),
                },
            ),
        ),
    ]
