# Generated by Django 2.2.4 on 2019-08-12 16:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0004_remove_teaser_and_demo_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasepage',
            name='body_streamfield_de',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('examples', wagtail.core.blocks.StructBlock([('examples', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], label='CTA Column')))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='usecasepage',
            name='body_streamfield_en',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('html', wagtail.core.blocks.RawHTMLBlock()), ('examples', wagtail.core.blocks.StructBlock([('examples', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.RichTextBlock(required=False)), ('link', wagtail.core.blocks.CharBlock(required=False)), ('link_text', wagtail.core.blocks.CharBlock(label='Link Text', max_length=50, required=False))], label='CTA Column')))]))], blank=True),
        ),
    ]
