# Generated by Django 2.2.4 on 2019-08-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0005_add_example_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasepage',
            name='image_caption_de',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Image Caption'),
        ),
        migrations.AddField(
            model_name='usecasepage',
            name='image_caption_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Image Caption'),
        ),
    ]
