# Generated by Django 2.2.4 on 2019-08-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0006_add_translatable_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecasepage',
            name='category',
            field=models.CharField(choices=[('MP', 'Municipalities'), ('CA', 'Citizen Assemblies'), ('CO', 'Co-Operatives'), ('NG', 'NGOs'), ('CP', 'Companies'), ('PO', 'Politicians')], max_length=2),
        ),
    ]
