# Generated by Django 2.2.4 on 2019-08-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_use_cases', '0009_remove_usecasepage_image_and_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecasepage',
            old_name='custom_image',
            new_name='image',
        ),
    ]
