shamefullyHoist: true
overrides:
  i18next-http-middleware: 3.9.7
blockExoticSubdeps: false
allowBuilds:
  husky: true
  adhocracy4@https://codeload.github.com/liqd/adhocracy4/tar.gz/b439eb9cb1c7205e5f207a0077dbdbc436ce5991: true
  '@parcel/watcher': true
