# Generated by Django 4.2.13 on 2024-08-27 11:36

import adhocracy4.images.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_ideas", "0004_alter_idea_item_ptr_alter_idea_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="image",
            field=adhocracy4.images.fields.ConfiguredImageField(
                "idea_image",
                blank=True,
                help_prefix="Visualize your idea.",
                upload_to="ideas/images/%Y/%m/%d/",
                verbose_name="Add image",
            ),
        ),
    ]
