# Generated by Django 5.2.8 on 2026-06-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_ideas", "0005_alter_idea_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="creator_contact_consent",
            field=models.BooleanField(default=False, verbose_name="Contact consent"),
        ),
        migrations.AddField(
            model_name="idea",
            name="creator_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="Your email address",
            ),
        ),
        migrations.AddField(
            model_name="idea",
            name="creator_phone",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Phone number"
            ),
        ),
    ]
