# Generated by Django 5.2.8 on 2026-06-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "a4_candy_ideas",
            "0006_idea_creator_contact_consent_idea_creator_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="creator_contact_consent",
            field=models.BooleanField(
                default=False, verbose_name="Creator contact consent"
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="creator_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="Creator email address",
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="creator_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Creator phone number",
            ),
        ),
    ]
