# Generated by Django 5.2.15 on 2026-10-07 13:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_ideas", "0007_alter_idea_creator_contact_consent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="is_reviewed",
            field=models.BooleanField(default=False, verbose_name="Reviewed"),
        ),
    ]
