# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:15
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_ideas'
         WHERE app_label = 'meinberlin_ideas';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'meinberlin_ideas';
                 WHERE app_label = 'a4_candy_ideas';"""


class Migration(migrations.Migration):

    replaces = [('liqd_product_ideas', '0016_update_content_types')]

    dependencies = [
        ('a4_candy_ideas', '0015_add_verbose_for_idea_image'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
