# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_ideas', '0017_rename_app_in_phase_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idea',
            table=None,
        ),
    ]
