# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 13:48
from __future__ import unicode_literals

from django.db import migrations


def rename_app(apps, schema_editor):
    Phase = apps.get_model("a4phases", "Phase")
    for phase in Phase.objects.all():
        phase.type = phase.type.replace(
            'liqd_product',
            'a4_candy')
        phase.save()


def backname_app(apps, schema_editor):
    Phase = apps.get_model("a4phases", "Phase")
    for phase in Phase.objects.all():
        phase.type = phase.type.replace(
            'a4_candy',
            'liqd_product')
        phase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_ideas', '0018_rename_table_to_default'),
    ]

    operations = [
        migrations.RunPython(rename_app, backname_app)
    ]
