# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 16:44
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_ideas'
         WHERE app_label = 'liqd_product_ideas';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'liqd_product_ideas';
                 WHERE app_label = 'a4_candy_ideas';"""


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_ideas', '0019_rename_app_in_phase_type'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
