# Generated by Django 2.2.19 on 2021-03-26 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4comments', '0007_comment_is_moderator_marked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('classification', models.CharField(choices=[('OFFENSIVE', 'Offensive'), ('OTHER', 'Other')], max_length=50)),
                ('comment_text', models.TextField(max_length=4000)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a4comments.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
