# Generated by Django 2.2.4 on 2019-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_news', '0002_max_length_teaser_and_rm_demo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='image_caption_de',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Image Caption'),
        ),
        migrations.AddField(
            model_name='newspage',
            name='image_caption_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Image Caption'),
        ),
    ]
