# Generated by Django 2.2.4 on 2019-08-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_news', '0004_newspage_custom_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='image_caption_de',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='image_caption_en',
        ),
    ]
