# Generated by Django 2.2.17 on 2020-11-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_questions', '0002_livestream'),
        ('a4_candy_interactive_events', '0001_initial'),
        ('a4phases', '0007_order_phases_also_by_id'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO a4_candy_interactive_events_livequestion (
                id,
                created,
                modified,
                text,
                is_answered,
                is_on_shortlist,
                is_hidden,
                is_live,
                category_id,
                module_id
            )
            SELECT
                id,
                created,
                modified,
                text,
                is_answered,
                is_on_shortlist,
                is_hidden,
                is_live,
                category_id,
                module_id
            FROM
                a4_candy_questions_question;
        """, reverse_sql="""
            INSERT INTO a4_candy_questions_question (
                id,
                created,
                modified,
                text,
                is_answered,
                is_on_shortlist,
                is_hidden,
                is_live,
                category_id,
                module_id
            )
            SELECT
                id,
                created,
                modified,
                text,
                is_answered,
                is_on_shortlist,
                is_hidden,
                is_live,
                category_id,
                module_id
            FROM
                a4_candy_interactive_events_livequestion;
        """),
        migrations.RunSQL("""
            INSERT INTO a4_candy_interactive_events_livestream2 (
                item_ptr_id,
                live_stream
            )
            SELECT
                item_ptr_id,
                live_stream
            FROM
                a4_candy_questions_livestream;
        """, reverse_sql="""
            INSERT INTO a4_candy_questions_livestream (
                item_ptr_id,
                live_stream
            )
            SELECT
                item_ptr_id,
                live_stream
            FROM
                a4_candy_interactive_events_livestream2;
        """),
        migrations.RunSQL("""
            UPDATE a4phases_phase
            SET type = 'a4_candy_interactive_events:issue'
            WHERE type = 'a4_candy_questions:issue'
        """, reverse_sql="""
            UPDATE a4phases_phase
            SET type = 'a4_candy_questions:issue'
            WHERE type = 'a4_candy_interactive_events:issue'
        """)
    ]
