# Generated by Django 2.2.17 on 2020-11-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_likes', '0001_initial'),
        ('a4_candy_interactive_events', '0001_initial'),
        ('a4_candy_questions', '0003_move_data'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO a4_candy_interactive_events_like (
                id,
                session,
                created,
                livequestion_id
            )
            SELECT
                id,
                session,
                created,
                question_id
            FROM
                a4_candy_likes_like;
        """, reverse_sql="""
            INSERT INTO a4_candy_likes_like (
                id,
                session,
                created,
                question_id
            )
            SELECT
                id,
                session,
                created,
                livequestion_id
            FROM
                a4_candy_interactive_events_like;
        """)
    ]
