# Generated by Django 2.2.17 on 2020-11-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_likes', '0002_move_data'),
    ]

    operations = [
        migrations.RunSQL("""
            DELETE FROM a4_candy_likes_like;
        """)
    ]
