# Generated by Django 2.2.3 on 2019-07-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('a4_candy_cms_contacts', '0002_customformsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='contact_person_image',
            field=models.ForeignKey(blank=True, help_text='The Image will be shown besides the name of the contact person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image of contact person'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
