# Generated by Django 2.2.4 on 2019-08-22 09:41

from django.db import migrations, models
import django.db.models.deletion


def set_custom_image_id(apps, schema_editor):
    CustomImage = apps.get_model('a4_candy_cms_images', 'CustomImage')
    FormPage = apps.get_model('a4_candy_cms_contacts', 'FormPage')

    for page in FormPage.objects.all():
        if page.contact_person_image:
            image = page.contact_person_image
            page.custom_contact_person_image_id = CustomImage.objects.get(id=image.id)
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_images', '0002_copy_images'),
        ('a4_candy_cms_contacts', '0003_add_contact_person_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='custom_contact_person_image',
            field=models.ForeignKey(blank=True, help_text='The Image will be shown besides the name of the contact person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a4_candy_cms_images.CustomImage', verbose_name='Image of contact person'),
        ),
        migrations.RunPython(set_custom_image_id),
    ]
