# Generated by Django 2.2.4 on 2019-08-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_contacts', '0005_remove_formpage_contact_person_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formpage',
            old_name='custom_contact_person_image',
            new_name='contact_person_image',
        ),
    ]
