# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:14
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'liqd_product_moderatorremark'
         WHERE app_label = 'meinberlin_moderatorremark';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'meinberlin_moderatorremark';
                 WHERE app_label = 'liqd_product_moderatorremark';"""


class Migration(migrations.Migration):

    replaces = [('liqd_product_moderatorremark', '0004_update_content_types')]

    dependencies = [
        ('a4_candy_moderatorremark', '0003_use_textfield'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
