# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_moderatorremark', '0004_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moderatorremark',
            table=None,
        ),
    ]
