# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_partners', '0002_extend_partner_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='about',
            new_name='information'
        ),
        migrations.AlterField(
            model_name='partner',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name='Information about your municipality'),
        )
    ]
