# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_partners', '0006_information_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='primary_colour',
            field=models.CharField(default='#008dc5', max_length=7),
        ),
        migrations.AddField(
            model_name='partner',
            name='secondary_colour',
            field=models.CharField(default='#00a747', max_length=7),
        ),
    ]
