# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_partners', '0006_information_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(default='Beteiligungsplattform', max_length=200),
        ),
    ]
