# Generated by Django 3.2.19 on 2023-11-22 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("a4_candy_ideas", "0002_rename_moderatorfeedback_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a4modules", "0007_verbose_name_created_modified"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdeaChoin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choins",
                    models.FloatField(blank=True, default=0, verbose_name="Choins"),
                ),
                (
                    "goal",
                    models.FloatField(blank=True, default=150, verbose_name="Goal"),
                ),
                (
                    "idea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a4_candy_ideas.idea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choins",
                    models.FloatField(blank=True, default=0, verbose_name="Choins"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a4modules.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "module")},
                "index_together": {("user", "module")},
            },
        ),
    ]
