# Generated by Django 3.2.19 on 2024-01-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_fairvote", "0002_userideachoin"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideachoin",
            name="missing",
            field=models.FloatField(
                blank=True, default=0, verbose_name="Missing Choins"
            ),
        ),
    ]
