# Generated by Django 3.2.19 on 2024-01-04 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_ideas", "0002_rename_moderatorfeedback_fields"),
        ("a4_candy_fairvote", "0003_ideachoin_missing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideachoin",
            name="idea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="choin",
                to="a4_candy_ideas.idea",
            ),
        ),
    ]
