# Generated by Django 3.2.19 on 2024-02-26 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a4modules", "0007_verbose_name_created_modified"),
        ("a4_candy_fairvote", "0005_alter_ideachoin_missing"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoinEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("ADD", "Add Choins"), ("ACC", "Idea Accepted")],
                        max_length=3,
                    ),
                ),
                ("content", models.TextField(blank=True, max_length=255)),
                (
                    "balance",
                    models.FloatField(blank=True, default=0, verbose_name="Balance"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="a4modules.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
