# Generated by Django 3.2.19 on 2024-03-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_fairvote", "0006_choinevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choinevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("NEW", "Welcome"),
                    ("ADD", "Add Choins"),
                    ("ACC", "Idea Accepted"),
                ],
                max_length=3,
            ),
        ),
    ]
