# Generated by Django 3.2.19 on 2024-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_fairvote", "0007_alter_choinevent_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="choinevent",
            name="content_params",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
