# Generated by Django 3.2.19 on 2024-05-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("a4projects", "0039_add_alt_text_to_field"),
        ("a4_candy_fairvote", "0008_choinevent_content_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="choin",
            name="supported_ideas_paid",
            field=models.FloatField(
                blank=True,
                default=0,
                verbose_name="Contribution to your supported ideas",
            ),
        ),
        migrations.CreateModel(
            name="ProjectChoin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid",
                    models.FloatField(
                        blank=True, default=0, verbose_name="Contribution to all ideas"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choin",
                        to="a4projects.project",
                    ),
                ),
            ],
        ),
    ]
