# Generated by Django 3.2.19 on 2024-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_fairvote", "0009_auto_20240506_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="ideachoin",
            name="order",
            field=models.IntegerField(blank=True, default=11, verbose_name="order"),
        ),
    ]
