# Generated by Django 3.2.19 on 2024-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_fairvote", "0010_ideachoin_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideachoin",
            name="goal",
            field=models.FloatField(blank=True, default=1000, verbose_name="Goal"),
        ),
        migrations.AlterField(
            model_name="ideachoin",
            name="missing",
            field=models.FloatField(
                blank=True, default=1000, verbose_name="Missing Choins"
            ),
        ),
        migrations.AlterField(
            model_name="ideachoin",
            name="order",
            field=models.IntegerField(blank=True, default=16, verbose_name="order"),
        ),
    ]
