# Generated by Django 2.2.20 on 2021-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_topicprio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
    ]
