# Generated by Django 3.2.19 on 2024-02-29 11:03

import adhocracy4.images.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_topicprio", "0002_topic_description_add_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                validators=[adhocracy4.images.validators.ImageAltTextValidator()],
                verbose_name="Description",
            ),
        ),
    ]
