# Generated by Django 2.2.10 on 2020-02-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('de', 'German')], default='de', help_text='Specify your preferred language for the user interface and the notifications of the platform.', max_length=4, verbose_name='Your preferred language'),
        ),
    ]
