# Generated by Django 2.2.13 on 2020-06-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0002_update_helptexts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('nl', 'Dutch')], default='de', help_text='Specify your preferred language for the user interface and the notifications of the platform.', max_length=4, verbose_name='Your preferred language'),
        ),
    ]
