# Generated by Django 3.2.13 on 2022-06-14 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_users", "0005_add_errormessage_for_username_already_used_as_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Email is invalid or already taken."},
                max_length=254,
                unique=True,
                verbose_name="Email address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "A user with that username already exists.",
                    "used_as_email": "This username is invalid.",
                },
                help_text="Required. 60 characters or fewer. Letters, digits, spaces and @/./+/-/_ only.",
                max_length=60,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[\\w]+[ \\w.@+-]*$",
                        "Enter a valid username. This value may contain only letters, digits, spaces and @/./+/-/_ characters. It must start with a digit or a letter.",
                        "invalid",
                    )
                ],
                verbose_name="username",
            ),
        ),
    ]
