# Generated by Django 4.2.13 on 2024-05-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_users", "0006_change_error_wording_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email address"),
        ),
    ]
