# Generated by Django 4.2.18 on 2025-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_users", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German")],
                default="de",
                help_text="Specify your preferred language for the user interface and the notifications of the platform.",
                max_length=4,
                verbose_name="Your preferred language",
            ),
        ),
    ]
