# Generated by Django 2.2.2 on 2019-07-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0008_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='de', help_text='Specify your preferred language for the user interface and the notifications of the platform.', max_length=4, verbose_name='Your preferred language'),
        ),
    ]
