# Generated by Django 5.1.11 on 2025-11-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_users", "0008_alter_user_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="get_notifications",
        ),
    ]
