# Generated by Django 2.2.5 on 2019-09-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0009_help_text_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='_avatar',
        ),
    ]
