# Generated by Django 2.2.6 on 2019-10-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_users', '0010_rename_avatar_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself in 255 characters!', max_length=255, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_handle',
            field=models.CharField(blank=True, help_text='Your facebook name is the last part of the URL, when you access your profile.', max_length=50, verbose_name='Facebook name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=15, verbose_name='Twitter handle'),
        ),
    ]
