# Generated by Django 2.2.17 on 2020-11-24 12:12

import adhocracy4.categories.fields
import adhocracy4.ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4categories', '0002_category_icon'),
        ('a4modules', '0005_module_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream2',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='a4modules.Item')),
                ('live_stream', adhocracy4.ckeditor.fields.RichTextCollapsibleUploadingField(blank=True, verbose_name='Live Stream')),
            ],
            options={
                'abstract': False,
            },
            bases=('a4modules.item',),
        ),
        migrations.CreateModel(
            name='LiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True)),
                ('text', models.TextField(max_length=1000, verbose_name='Question')),
                ('is_answered', models.BooleanField(default=False)),
                ('is_on_shortlist', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('category', adhocracy4.categories.fields.CategoryField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='a4categories.Category', verbose_name='Characteristic')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a4modules.Module')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('livequestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livequestion_likes', to='a4_candy_interactive_events.LiveQuestion')),
            ],
            options={
                'unique_together': {('session', 'livequestion')},
            },
        ),
    ]
