# Generated by Django 2.2.20 on 2021-05-03 07:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4modules', '0005_module_is_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a4_candy_interactive_events', '0001_initial'),
        ('a4_candy_questions', '0003_move_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveStream2',
            new_name='ExtraFieldsInteractiveEvent',
        ),
    ]
