# Generated by Django 5.1.11 on 2025-10-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "a4_candy_interactive_events",
            "0006_alter_extrafieldsinteractiveevent_live_stream",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extrafieldsinteractiveevent",
            options={"base_manager_name": "objects"},
        ),
    ]
