# Generated by Django 2.2.17 on 2020-11-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_newsletters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="When adding images, please ensure to set the width no larger than 600px.",
                verbose_name="Email body",
            ),
        ),
    ]
