# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:13
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'liqd_product_moderatorfeedback'
         WHERE app_label = 'meinberlin_moderatorfeedback';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'meinberlin_moderatorfeedback';
                 WHERE app_label = 'liqd_product_moderatorfeedback';"""


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_moderatorfeedback', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
