# Generated by Django 3.2.16 on 2023-01-16 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("a4_candy_moderatorfeedback", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ModeratorStatement",
            new_name="ModeratorFeedback",
        ),
    ]
