# Generated by Django 2.2.4 on 2019-09-09 13:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_moderatorfeedback', '0004_update_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorstatement',
            name='statement',
            field=ckeditor.fields.RichTextField(blank=True, help_text='The official feedback will appear below the idea, indicating your organisation. The idea provider receives a notification.', verbose_name='Official feedback'),
        ),
    ]
