# Generated by Django 3.2.19 on 2024-03-26 10:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_moderatorfeedback", "0005_moderatorcommentfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderatorcommentfeedback",
            name="feedback_text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Moderator feedback"
            ),
        ),
        migrations.AlterField(
            model_name="moderatorfeedback",
            name="feedback_text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Official feedback"
            ),
        ),
    ]
