# Generated by Django 2.2.4 on 2019-08-22 09:16

from django.db import migrations


def copy_images(apps, schema_editor):
    CustomImage = apps.get_model('a4_candy_cms_images', 'CustomImage')
    Image = apps.get_model('wagtailimages', 'Image')

    for image in Image.objects.all():
        CustomImage.objects.create(
            id = image.id,
            title = image.title,
            file = image.file,
            width = image.width,
            height = image.height,
            created_at = image.created_at,
            focal_point_x = image.focal_point_x,
            focal_point_y = image.focal_point_y,
            uploaded_by_user = image.uploaded_by_user,
            file_size = image.file_size,
            collection_id = image.collection_id
        )


def delete_images(apps, schema_editor):
    CustomImage = apps.get_model('a4_candy_cms_images', 'CustomImage')

    CustomImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_images, delete_images),
    ]
