# Generated by Django 3.2.13 on 2022-06-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_cms_images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customimage",
            name="file_hash",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=40
            ),
        ),
    ]
