# Generated by Django 4.2.17 on 2024-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_cms_images", "0004_alter_customrendition_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="customimage",
            name="description",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="description"
            ),
        ),
    ]
