# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:15
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'liqd_product_mapideas'
         WHERE app_label = 'meinberlin_mapideas';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'meinberlin_mapideas';
                 WHERE app_label = 'liqd_product_mapideas';"""


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_mapideas', '0018_point_helptext'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
