# Generated by Django 5.2.8 on 2026-02-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4_candy_contrib", "0001_drop_background_task_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for this setting (e.g. project_summary_prompt).",
                        max_length=255,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Stored value. Empty value falls back to the default from the registry.",
                        verbose_name="Value",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
                "ordering": ["key"],
            },
        ),
    ]
