# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import ckeditor.fields
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('meinberlin_documents', '0001_initial'), ('meinberlin_documents', '0002_rename_document_to_chapter')]

    initial = True

    dependencies = [
        ('a4modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('item_ptr', models.OneToOneField(primary_key=True, serialize=False, auto_created=True, parent_link=True, to='a4modules.Item')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'meinberlin_documents_chapter',
            },
            bases=('a4modules.item',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(blank=True, null=True, editable=False)),
                ('name', models.CharField(max_length=120, blank=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('weight', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(related_name='paragraphs', to='liqd_product_documents.Chapter')),
            ],
            options={
                'ordering': ('weight',),
                'db_table': 'meinberlin_documents_paragraph',
            },
        ),
    ]
