# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 09:09
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_cms_settings'
         WHERE app_label = 'liqd_product_cms_settings';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'liqd_product_cms_settings';
                 WHERE app_label = 'a4_candy_cms_settings';"""


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
