# Generated by Django 2.2.10 on 2020-03-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('a4_candy_cms_settings', '0003_add_default_social_media_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='netiquette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_page_netiquette', to='wagtailcore.Page'),
        ),
    ]
