# Generated by Django 2.2.17 on 2021-01-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_settings', '0004_importantpages_netiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsettings',
            name='platform_name',
            field=models.CharField(default='adhocracy+', max_length=20, verbose_name='Platform name'),
        ),
    ]
