# Generated by Django 2.2.3 on 2019-08-02 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('a4_candy_cms_settings', '0004_organisationsettings_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='important_page_contact', to='wagtailcore.Page'),
        ),
    ]
