# Generated by Django 2.2.3 on 2019-08-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_cms_settings', '0005_importantpages_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantpages',
            name='donate_link',
            field=models.URLField(blank=True),
        ),
    ]
