# Generated by Django 4.2.7 on 2024-04-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("a4_candy_cms_settings", "0006_add_helptexts_to_organisation_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="importantpages",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="important_page_registration",
                to="wagtailcore.page",
            ),
        ),
    ]
