# Generated by Django 5.2.15 on 2026-08-26 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a4modules', '0010_populate_item_polymorphic_ctype'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedBallot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Modified')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_ballots', to='a4modules.module')),
            ],
            options={
                'ordering': ['-created'],
                'unique_together': {('module', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='RankedChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_winners', models.PositiveSmallIntegerField(default=3, help_text='How many ideas should be selected from the ranked votes. The top N ideas are considered the winners.', verbose_name='Number of winners')),
                ('hide_results_until_finished', models.BooleanField(default=True, verbose_name='Hide results until participation is over')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_choice', to='a4modules.module')),
            ],
            options={
                'verbose_name': 'Ranked choice',
                'verbose_name_plural': 'Ranked choices',
            },
        ),
        migrations.CreateModel(
            name='RankedEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_pk', models.PositiveIntegerField()),
                ('rank', models.PositiveSmallIntegerField()),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='a4_candy_ranked_choice.rankedballot')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_pk'], name='a4_candy_ra_content_f0bca1_idx')],
                'unique_together': {('ballot', 'content_type', 'object_pk')},
            },
        ),
    ]
