# Generated by Django 2.2.24 on 2021-09-16 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a4modules', '0005_module_is_draft'),
        ('a4_candy_polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='APlusChoice',
        ),
        migrations.RenameModel(
            old_name='Poll',
            new_name='APlusPoll',
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='APlusQuestion',
        ),
        migrations.RenameModel(
            old_name='Vote',
            new_name='APlusVote',
        ),
    ]
