# Generated by Django 2.2.24 on 2021-09-16 09:34

from django.db import migrations


def copy_data(apps, schema_editor):
    Item = apps.get_model('a4modules', 'Item')
    APlusPoll = apps.get_model('a4_candy_polls', 'APlusPoll')
    Poll = apps.get_model('a4polls', 'Poll')
    APlusQuestion = apps.get_model('a4_candy_polls', 'APlusQuestion')
    Question = apps.get_model('a4polls', 'Question')
    APlusChoice = apps.get_model('a4_candy_polls', 'APlusChoice')
    Choice = apps.get_model('a4polls', 'Choice')
    APlusVote = apps.get_model('a4_candy_polls', 'APlusVote')
    Vote = apps.get_model('a4polls', 'Vote')

    for aplus_poll in APlusPoll.objects.all():
        item = Item.objects.get(id=aplus_poll.item_ptr_id)
        poll = Poll(item_ptr_id=aplus_poll.item_ptr_id)
        poll.__dict__.update(item.__dict__)
        poll.save()
        aplus_questions = APlusQuestion.objects.filter(poll=aplus_poll)
        for aplus_question in aplus_questions:
            question = Question.objects.create(
                label = aplus_question.label,
                weight = aplus_question.weight,
                multiple_choice = aplus_question.multiple_choice,
                poll = poll)
            aplus_choices = APlusChoice.objects.filter(question=aplus_question)
            for i, aplus_choice in enumerate(aplus_choices):
                choice = Choice.objects.create(
                    label = aplus_choice.label,
                    question = question,
                    weight = i)
                aplus_votes = APlusVote.objects.filter(choice=aplus_choice)
                for aplus_vote in aplus_votes:
                    Vote.objects.create(
                        created = aplus_vote.created,
                        modified = aplus_vote.modified,
                        creator = aplus_vote.creator,
                        choice = choice)

    # change content types from old to new poll
    Comment = apps.get_model('a4comments', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    aplus_poll_content_type = ContentType.objects.get_for_model(APlusPoll)
    poll_content_type = ContentType.objects.get_for_model(Poll)
    comments = Comment.objects.filter(content_type_id=aplus_poll_content_type.id)
    for comment in comments:
        comment.content_type = poll_content_type
        comment.save()
    Action = apps.get_model('a4actions', 'Action')
    actions = Action.objects.filter(target_content_type_id=aplus_poll_content_type.id)
    for action in actions:
        action.target_content_type = poll_content_type
        action.save()

    Phase = apps.get_model('a4phases', 'Phase')
    phases = Phase.objects.filter(type='a4_candy_polls:voting')
    for phase in phases:
        phase.type='a4polls:voting'
        phase.save()


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_polls', '0002_rename_aplus_poll_models'),
        ('a4polls', '0004_change_wording_helptext'),
        ('a4comments', '0007_comment_is_moderator_marked'),
        ('a4phases', '0007_order_phases_also_by_id'),
        ('a4actions', '0004_auto_20181204_1650')
    ]

    operations = [
        migrations.RunPython(copy_data)
    ]
