# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('meinberlin_polls', '0004_question_multiple_choice')]

    dependencies = [
        ('a4_candy_polls', '0003_choice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
