# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_polls', '0005_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='poll',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='vote',
            table=None,
        ),
    ]
