# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 15:30
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_polls'
         WHERE app_label = 'liqd_product_polls';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'liqd_product_polls';
                 WHERE app_label = 'a4_candy_polls';"""


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_polls', '0006_rename_tables_to_default'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
