# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('meinberlin_budgeting', '0017_proposal_labels')]

    dependencies = [
        ('a4labels', '0001_initial'),
        ('liqd_product_budgeting', '0016_add_form_hint_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='labels',
            field=models.ManyToManyField(related_name='liqd_product_budgeting_proposal_label', to='a4labels.Label'),
        ),
    ]
