# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 15:15
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'liqd_product_budgeting'
         WHERE app_label = 'meinberlin_budgeting';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'meinberlin_budgeting';
                 WHERE app_label = 'liqd_product_budgeting';"""


class Migration(migrations.Migration):

    dependencies = [
        ('liqd_product_budgeting', '0020_point_helptext'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
