# Generated by Django 3.2.16 on 2023-01-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_budgeting", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proposal",
            old_name="moderator_statement",
            new_name="moderator_feedback_text",
        ),
        migrations.RenameField(
            model_name="proposal",
            old_name="moderator_feedback",
            new_name="moderator_status",
        ),
    ]
