# Generated by Django 3.2.19 on 2024-03-26 10:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_budgeting", "0002_rename_moderatorfeedback_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
        ),
    ]
