# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 14:41
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE a4phases_phase
         SET type = REPLACE(type, 'liqd_product_budgeting', 'a4_candy_budgeting');"""

reverse_sql = """UPDATE a4phases_phase
                 SET type = REPLACE(type, 'a4_candy_budgeting', 'liqd_product_budgeting');"""

class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_budgeting', '0022_update_content_types'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
