# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('a4_candy_budgeting', '0022_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proposal',
            table=None,
        ),
    ]
