# Generated by Django 5.1.11 on 2025-10-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_activities", "0003_alter_activity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"base_manager_name": "objects"},
        ),
    ]
