# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 16:35
from __future__ import unicode_literals

from django.db import migrations

sql = """UPDATE django_content_type
         SET app_label = 'a4_candy_activities'
         WHERE app_label = 'liqd_product_activities';"""

reverse_sql = """UPDATE django_content_type
                 SET app_label = 'liqd_product_activities';
                 WHERE app_label = 'a4_candy_activities';"""


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_activities', '0005_rename_table_to_default'),
    ]

    operations = [
        migrations.RunSQL(sql, reverse_sql)
    ]
