# Generated by Django 5.2.8 on 2026-02-09 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4projects", "0053_alter_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The prompt used for summarization",
                        verbose_name="Prompt",
                    ),
                ),
                (
                    "input_text_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash of the input text for quick comparison",
                        max_length=64,
                        verbose_name="Input Text Hash",
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(
                        help_text="The complete SummaryResponse data structure",
                        verbose_name="Response Data",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the summary was created",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="a4projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Summary",
                "verbose_name_plural": "Project Summaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "input_text_hash"],
                        name="a4_candy_su_project_390047_idx",
                    )
                ],
            },
        ),
    ]
