# Generated by Django 5.2.8 on 2026-03-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_summarization", "0002_projectsummary_last_checked_at"),
        ("a4_candy_summarization", "0002_summaryfeedback"),
    ]

    operations = []
