# Generated by Django 5.2.8 on 2026-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StatisticsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Stat"),
                            ("testimonial", "Testimonial"),
                            ("image", "Image"),
                        ],
                        max_length=20,
                    ),
                ),
                ("header", models.CharField(blank=True, max_length=200)),
                ("subheader", models.CharField(blank=True, max_length=300)),
                ("quote", models.TextField(blank=True)),
                ("person_name", models.CharField(blank=True, max_length=100)),
                ("person_description", models.CharField(blank=True, max_length=200)),
                (
                    "person_image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="statistics/"),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
