# Generated by Django 5.2.8 on 2026-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticsitem",
            name="image_alt_text",
            field=models.TextField(blank=True),
        ),
    ]
