# Generated by Django 5.2.8 on 2026-05-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0002_statisticsitem_image_alt_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statisticsitem",
            old_name="header",
            new_name="header_en",
        ),
        migrations.RenameField(
            model_name="statisticsitem",
            old_name="image_alt_text",
            new_name="image_alt_text_en",
        ),
        migrations.RenameField(
            model_name="statisticsitem",
            old_name="person_description",
            new_name="person_description_en",
        ),
        migrations.RenameField(
            model_name="statisticsitem",
            old_name="quote",
            new_name="quote_en",
        ),
        migrations.RenameField(
            model_name="statisticsitem",
            old_name="subheader",
            new_name="subheader_en",
        ),
        migrations.RemoveField(
            model_name="statisticsitem",
            name="person_name",
        ),
        migrations.AddField(
            model_name="statisticsitem",
            name="header_de",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="statisticsitem",
            name="image_alt_text_de",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="statisticsitem",
            name="person_description_de",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="statisticsitem",
            name="quote_de",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="statisticsitem",
            name="subheader_de",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
