# Generated by Django 5.2.8 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0003_rename_header_statisticsitem_header_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statisticsitem",
            name="person_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
