# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0002_update_content_types'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organisation',
            table=None,
        ),
    ]
