# Generated by Django 2.2.8 on 2020-01-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_organisations", "0002_organisation_image_copyright"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="information",
            field=models.TextField(
                blank=True,
                help_text="You can provide general information about your participation platform to your visitors. It’s also helpful to name a general person of contact for inquiries. The information will be shown on a separate page that can be reached via the main menu.",
                verbose_name="Information about your organisation",
            ),
        ),
    ]
