# Generated by Django 2.2.3 on 2019-07-25 09:12

from django.db import migrations


def copy_partner_data(apps, schema_editor):
    '''
    We can't import the model directly as it may be a newer
    versions than this migration expects. We use the historical version.
    '''
    Organisation = apps.get_model('a4_candy_organisations', 'Organisation')
    for organisation in Organisation.objects.all():
        if organisation.partner:
            for admin in organisation.partner.admins.all():
                if not admin in organisation.initiators.all():
                    organisation.initiators.add(admin)
            organisation.description = organisation.partner.description
            organisation.image = organisation.partner.image
            organisation.imprint = organisation.partner.imprint
            organisation.information = organisation.partner.information
            organisation.logo = organisation.partner.logo
            organisation.slogan = organisation.partner.slogan
            organisation.title = organisation.partner.title
            organisation.save()

class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0004_copy_fields_from_partners'),
    ]

    operations = [
        migrations.RunPython(copy_partner_data),
    ]
