# Generated by Django 2.2.3 on 2019-07-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0005_copy_partner_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='partner',
        ),
    ]
