# Generated by Django 2.2.6 on 2019-10-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0006_remove_organisation_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='is_supporting',
            field=models.BooleanField(default=False),
        ),
    ]
