# Generated by Django 2.2.10 on 2020-02-20 10:46

import adhocracy4.ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0007_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='information',
            field=adhocracy4.ckeditor.fields.RichTextCollapsibleUploadingField(blank=True, help_text='You can provide general information about your participation platform to your visitors. It’s also helpful to name a general person of contact for inquiries. The information will be shown on a separate "About" page that can be reached via the main menu.', verbose_name='Information about your organisation'),
        ),
    ]
