# Generated by Django 2.2.6 on 2019-10-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0007_organisation_is_supporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='is_supporting',
            field=models.BooleanField(default=False, help_text='For supporting organisations, the banner asking for donations is not displayed on their pages.', verbose_name='is a supporting organisation'),
        ),
    ]
