# Generated by Django 2.2.10 on 2020-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0008_org_info_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
