# Generated by Django 2.2.16 on 2020-09-21 09:44

from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def forwards_func(apps, schema_editor):
    Organisation = apps.get_model('a4_candy_organisations', 'Organisation')
    OrganisationTranslation = apps.get_model('a4_candy_organisations', 'OrganisationTranslation')

    for organisation in Organisation.objects.all():
        OrganisationTranslation.objects.create(
            master_id=organisation.pk,
            language_code=settings.DEFAULT_USER_LANGUAGE_CODE,
            description=organisation.description_untranslated,
            slogan=organisation.slogan_untranslated,
            information=organisation.information_untranslated,
        )


def backwards_func(apps, schema_editor):
    Organisation = apps.get_model('a4_candy_organisations', 'Organisation')
    OrganisationTranslation = apps.get_model('a4_candy_organisations', 'OrganisationTranslation')

    for object in Organisation.objects.all():
        translation = _get_translation(object, OrganisationTranslation)
        object.description_untranslated = translation.description
        object.slogan_untranslated = translation.slogan
        object.information_untranslated = translation.information
        object.save()   # Note this only calls Model.save()


def _get_translation(organisation, OrganisationTranslation):
    translations = OrganisationTranslation.objects.filter(master_id=organisation.pk)
    try:
        return translations.get(language_code=settings.DEFAULT_USER_LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            return translations.get(language_code=settings.LANGUAGE_CODE)
        except ObjectDoesNotExist:
            # Maybe the object was translated only in a specific language?
            # Hope there is a single translation
            return translations.get()


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0014_add_translatable_fields_and_rename_odl_fields'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
