# Generated by Django 2.2.16 on 2020-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a4_candy_organisations', '0015_migrate_untranslated_fields_to_translatable_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('nl', 'Dutch')], default='de', help_text='All e-mails to unregistered users (invites) will be sent in this language.', max_length=4, verbose_name='Default language for e-mails'),
        ),
    ]
