# Generated by Django 3.2.20 on 2023-11-16 11:35

from bs4 import BeautifulSoup
from django.db import migrations
from django.utils import translation


def replace_iframe_with_figur(apps, schema_editor):
    template = (
        '<figure class="media"><div data-oembed-url="{url}"><div><iframe src="'
        '{url}"></iframe></div></div></figure>'
    )
    Organisation = apps.get_model("a4_candy_organisations", "Organisation")
    translation.activate("en")

    for organisation in Organisation.objects.all():
        soup = BeautifulSoup(organisation.description, "html.parser")
        iframes = soup.findAll("iframe")
        for iframe in iframes:
            figure = BeautifulSoup(
                template.format(url=iframe.attrs["src"]), "html.parser"
            )
            iframe.replaceWith(figure)
        if iframes:
            organisation.description = soup.prettify(formatter="html")
            organisation.save()


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_organisations", "0021_alter_organisation_logo"),
    ]

    operations = [
        migrations.RunPython(
            replace_iframe_with_figur,
        ),
    ]
