# Generated by Django 3.2.19 on 2024-03-14 12:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_organisations", "0021_alter_organisation_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisationtranslation",
            name="information",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text='You can provide general information about your participation platform to your visitors. It’s also helpful to name a general person of contact for inquiries. The information will be shown on a separate "About" page that can be reached via the main menu.',
                verbose_name="Information about your organisation",
            ),
        ),
    ]
