# Generated by Django 4.2.7 on 2024-08-08 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_organisations", "0023_alter_organisation_language"),
        ("a4_candy_organisations", "0023_auto_20240328_1138"),
    ]

    operations = []
