# Generated by Django 4.2.18 on 2025-01-20 15:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_organisations", "0024_organisation_enable_geolocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=True, populate_from="name", unique=True
            ),
        ),
    ]
