# Generated by Django 4.2.18 on 2025-05-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_organisations", "0025_alter_organisation_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("de", "German")],
                default="de",
                help_text="All e-mails to unregistered users (invites) will be sent in this language.",
                max_length=4,
                verbose_name="Default language for e-mails",
            ),
        ),
    ]
