# Generated by Django 4.2.7 on 2024-08-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("a4_candy_organisations", "0025_alter_organisation_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("nl", "Dutch"),
                    ("ky", "Kyrgyz"),
                    ("ru", "Russian"),
                    ("he", "Hebrew"),
                ],
                default="en",
                help_text="All e-mails to unregistered users (invites) will be sent in this language.",
                max_length=4,
                verbose_name="Default language for e-mails",
            ),
        ),
    ]
