# Generated by Django 5.1.11 on 2025-08-31 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a4actions", "0010_alter_action_verb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("project_update", "Project Update"),
                            ("project_event", "Project Event"),
                            ("user_engagement", "User Engagement"),
                            ("moderator_feedback", "Moderator Feedback"),
                            ("newsletter", "Newsletter"),
                            ("system", "System Notification"),
                        ],
                        max_length=20,
                        verbose_name="Notification Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "target_url",
                    models.URLField(blank=True, null=True, verbose_name="Target URL"),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="a4actions.action",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_newsletter",
                    models.BooleanField(
                        default=False, verbose_name="Receive email newsletter"
                    ),
                ),
                (
                    "notify_project_updates",
                    models.BooleanField(
                        default=True,
                        help_text="Includes phase changes, new content in followed projects",
                        verbose_name="Receive notifications for updates in followed projects",
                    ),
                ),
                (
                    "notify_project_events",
                    models.BooleanField(
                        default=True,
                        help_text="Get notified about upcoming offline events",
                        verbose_name="Receive notifications about events in followed projects",
                    ),
                ),
                (
                    "notify_user_engagement",
                    models.BooleanField(
                        default=True,
                        help_text="Comments, ratings, and reactions to your inputs",
                        verbose_name="Receive notifications when users react to your content",
                    ),
                ),
                (
                    "email_project_updates",
                    models.BooleanField(
                        default=True, verbose_name="Email me about project updates"
                    ),
                ),
                (
                    "email_project_events",
                    models.BooleanField(
                        default=True, verbose_name="Email me about events"
                    ),
                ),
                (
                    "email_user_engagement",
                    models.BooleanField(
                        default=True,
                        verbose_name="Email me about reactions to my content",
                    ),
                ),
                ("track_project_updates", models.BooleanField(default=True)),
                ("track_project_events", models.BooleanField(default=True)),
                ("track_user_engagement", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
    ]
