# Generated by Django 5.1.11 on 2025-09-07 16:47

import apps.notifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4actions", "0010_alter_action_verb"),
        ("a4phases", "0007_order_phases_also_by_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("phase_started", "Phase Started"),
                            ("phase_ended", "Phase Ended"),
                            ("project_started", "Project Started"),
                            ("project_completed", "Project Completed"),
                            ("project_status_change", "Project Status Change"),
                            ("project_update", "Project Update"),
                            ("project_event", "Project Event"),
                            ("event_added", "Event Added"),
                            ("event_soon", "Event Starting Soon"),
                            ("event_update", "Event Update"),
                            ("event_cancelled", "Event Cancelled"),
                            ("newsletter", "Newsletter"),
                            ("user_engagement", "User Engagement"),
                            ("message_received", "Message Received"),
                            ("project_invitation", "Project Invitation"),
                            ("comment_reply", "Comment Reply"),
                            ("content_reaction", "Content Reaction"),
                            ("moderator_feedback", "Moderator Feedback"),
                            ("moderator_action", "Moderator Action"),
                            ("content_approved", "Content Approved"),
                            ("content_rejected", "Content Rejected"),
                            ("user_warning", "User Warning"),
                            ("content_flagged", "Content Flagged"),
                            ("system", "System Notification"),
                        ],
                        max_length=30,
                        verbose_name="Notification Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("message", models.TextField(verbose_name="Message")),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "target_url",
                    models.URLField(blank=True, null=True, verbose_name="Target URL"),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="a4actions.action",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict, encoder=apps.notifications.models.LazyEncoder
                    ),
                ),
                ("message_template", models.CharField(default="", max_length=255)),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_newsletter",
                    models.BooleanField(default=True, verbose_name="Email newsletter"),
                ),
                (
                    "notify_project_updates",
                    models.BooleanField(
                        default=True, verbose_name="In-app project updates"
                    ),
                ),
                (
                    "notify_project_events",
                    models.BooleanField(
                        default=True, verbose_name="In-app project events"
                    ),
                ),
                (
                    "notify_user_engagement",
                    models.BooleanField(
                        default=True, verbose_name="In-app user interactions"
                    ),
                ),
                (
                    "email_project_updates",
                    models.BooleanField(
                        default=True, verbose_name="Email project updates"
                    ),
                ),
                (
                    "email_project_events",
                    models.BooleanField(
                        default=True, verbose_name="Email project events"
                    ),
                ),
                (
                    "email_user_engagement",
                    models.BooleanField(
                        default=True, verbose_name="Email user interactions"
                    ),
                ),
                ("track_project_updates", models.BooleanField(default=True)),
                ("track_project_events", models.BooleanField(default=True)),
                ("track_user_engagement", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_invitations",
                    models.BooleanField(default=True, verbose_name="Email invitations"),
                ),
                (
                    "email_messages",
                    models.BooleanField(default=True, verbose_name="Email messages"),
                ),
                (
                    "email_moderation",
                    models.BooleanField(
                        default=True, verbose_name="Email moderation actions"
                    ),
                ),
                (
                    "email_warnings",
                    models.BooleanField(default=True, verbose_name="Email warnings"),
                ),
                (
                    "notify_invitations",
                    models.BooleanField(
                        default=True, verbose_name="In-app invitations"
                    ),
                ),
                (
                    "notify_messages",
                    models.BooleanField(default=True, verbose_name="In-app messages"),
                ),
                (
                    "notify_moderation",
                    models.BooleanField(
                        default=True, verbose_name="In-app moderation actions"
                    ),
                ),
                (
                    "notify_warnings",
                    models.BooleanField(default=True, verbose_name="In-app warnings"),
                ),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
            },
        ),
        migrations.CreateModel(
            name="PhaseChangeNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("start_24h", "24h Before Start"),
                            ("end_24h", "24h Before End"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advance_notifications",
                        to="a4phases.phase",
                    ),
                ),
            ],
            options={
                "unique_together": {("phase", "notification_type")},
            },
        ),
    ]
