# Generated by Django 5.1.11 on 2025-09-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("phase_started", "Phase Started"),
                    ("phase_ended", "Phase Ended"),
                    ("project_started", "Project Started"),
                    ("project_completed", "Project Completed"),
                    ("project_status_change", "Project Status Change"),
                    ("project_update", "Project Update"),
                    ("project_event", "Project Event"),
                    ("event_added", "Event Added"),
                    ("event_soon", "Event Starting Soon"),
                    ("event_update", "Event Update"),
                    ("event_cancelled", "Event Cancelled"),
                    ("newsletter", "Newsletter"),
                    ("user_engagement", "User Engagement"),
                    ("message_received", "Message Received"),
                    ("project_invitation", "Project Invitation"),
                    ("comment_reply", "Comment Reply"),
                    ("comment_on_post", "Comment on Post"),
                    ("content_reaction", "Content Reaction"),
                    ("moderator_highlight", "Moderator Highlight"),
                    ("moderator_feedback", "Moderator Feedback"),
                    ("moderator_blocked_comment", "Moderator Blocked Comment"),
                    ("moderator_idea_feedback", "Moderator Idea Feedback"),
                    ("moderator_action", "Moderator Action"),
                    ("content_approved", "Content Approved"),
                    ("content_rejected", "Content Rejected"),
                    ("user_warning", "User Warning"),
                    ("content_flagged", "Content Flagged"),
                    ("system", "System Notification"),
                ],
                max_length=30,
                verbose_name="Notification Type",
            ),
        ),
    ]
