# Generated by Django 5.1.11 on 2025-09-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhaseChangeNotification",
        ),
    ]
