# Generated by Django 5.2.8 on 2026-01-26 15:12

from django.db import migrations
from django.db import migrations, models

translation_map = {
    "Die Moderation hat Ihr Kommentar {comment} im Projekt {project} hervorgehoben.": "A moderator highlighted your comment '{comment}' in project {project}",
    "{user} hat Ihren Beitrag {post} kommentiert": "{user} commented on your post {post}",
    "{user} hat auf {comment} geantwortet": "{user} replied to your {comment}",
    'Eine neue Veranstaltung "{event}" wurde dem Projekt {project} hinzugefügt.': "A new event '{event}' has been added to the project {project}",
    'Die Veranstaltung "{event}" im Projekt {project} wurde abgesagt.': "The event '{event}' in project {project} has been cancelled",
    'Die Veranstaltung "{event}" im Projekt {project} startet am {event_date}': "The event '{event}' in project {project} is starting on {event_date}",
    "Die Veranstaltung {event} im Projekt {project} wurde aktualisiert": "The event {event} in project {project} has been updated",
    "Die Moderation hat Feedback zu {comment} gegeben": "A moderator gave feedback on your {comment}",
    "Die Moderation hat Feedback zu Ihrer Idee {idea} gegeben": "A moderator gave feedback on your idea {idea}",
    "Die Moderation hat Feedback zu Ihrem Vorschlag {proposal} gegeben": "A moderator gave feedback on your proposal {proposal}",
    "Ihr Kommentar im Projekt {project_name} von der Moderation blockiert": "Your comment was blocked in project {project_name}",
    "Das Projekt {project} hat begonnen.": "The project {project} has begun.",
    "{project_name} ist beendet.": "{project_name} has completed.",
    "Das Projekt {project} wurde beendet.": "The project {project} has been completed.",
    "Sie wurden zum Projekt {project} eingeladen. Bitte überprüfen Sie ihre E-Mails, um die Einladung anzunehmen.": "You have been invited to project {project}. Please check your email to accept.",
    "Sie habe eine Einladung zur Moderation im Projekt %(project_name)s erhalten. {invitation} ansehen": "You have been invited to be a moderator of project %(project_name)s. View {invitation}",
    "Neues Projekt {project} wurde erstellt.": "A new project {project} has been created.",
    "Das Projekt {project} wurde gelöscht.": "The project {project} has been deleted.",
    '{content_type} "{content}" wurde im Projekt {project} erstellt.': 'A new {content_type} "{content}" has been created in project {project}.',
}


def forward_migrate_message_templates(apps, schema_editor):
    Notification = apps.get_model("a4_candy_notifications", "Notification")

    for notification in Notification.objects.all():
        current_message = notification.message_template
        if current_message in translation_map:
            notification.message_key = translation_map[current_message]
        else:
            # If not in map, it is already in english
            notification.message_key = current_message
        notification.save()


def backward_migrate_message_templates(apps, schema_editor):
    # For rollback, can't restore translations - would need to translate back
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message_key",
            field=models.CharField(max_length=500, default="", blank=True),
        ),
        migrations.RunPython(
            forward_migrate_message_templates,
        ),
    ]
