# Generated by Django 5.1.11 on 2025-09-22 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="title",
        ),
    ]
