# Generated by Django 5.2.15 on 2026-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "a4_candy_notifications",
            "0003_notificationsettings_email_initiator_publish_results",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("phase_started", "Phase Started"),
                    ("phase_ended", "Phase Ended"),
                    ("project_started", "Project Started"),
                    ("project_completed", "Project Completed"),
                    ("project_created", "Project Created"),
                    ("project_deleted", "Project Deleted"),
                    ("organisation_new_project", "New Project from Organisation"),
                    ("user_content_created", "User Content created"),
                    ("event_added", "Event Added"),
                    ("event_soon", "Event Starting Soon"),
                    ("event_update", "Event Update"),
                    ("event_cancelled", "Event Cancelled"),
                    ("project_moderation_invitation", "Project Moderation Invitation"),
                    ("project_invitation", "Project Invitation"),
                    ("comment_reply", "Comment Reply"),
                    ("comment_on_post", "Comment on Post"),
                    ("moderator_highlight", "Moderator Highlight"),
                    ("moderator_comment_feedback", "Moderator Comment Feedback"),
                    ("moderator_blocked_comment", "Moderator Blocked Comment"),
                    ("moderator_idea_feedback", "Moderator Idea Feedback"),
                    ("system", "System Notification"),
                ],
                max_length=30,
                verbose_name="Notification Type",
            ),
        ),
    ]
