# Generated by Django 5.1.11 on 2025-09-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0004_add_notification_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("phase_started", "Phase Started"),
                    ("phase_ended", "Phase Ended"),
                    ("project_started", "Project Started"),
                    ("project_completed", "Project Completed"),
                    ("event_added", "Event Added"),
                    ("event_soon", "Event Starting Soon"),
                    ("event_update", "Event Update"),
                    ("event_cancelled", "Event Cancelled"),
                    ("project_invitation", "Project Invitation"),
                    ("comment_reply", "Comment Reply"),
                    ("comment_on_post", "Comment on Post"),
                    ("moderator_highlight", "Moderator Highlight"),
                    ("moderator_feedback", "Moderator Feedback"),
                    ("moderator_blocked_comment", "Moderator Blocked Comment"),
                    ("moderator_idea_feedback", "Moderator Idea Feedback"),
                    ("system", "System Notification"),
                ],
                max_length=30,
                verbose_name="Notification Type",
            ),
        ),
    ]
