# Generated by Django 5.2.15 on 2026-08-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0004_alter_notification_notification_type"),
        ("a4projects", "0055_alter_project_allow_guest_users_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="a4projects.project",
                verbose_name="Project",
            ),
        ),
    ]
