# Generated by Django 5.2.15 on 2026-08-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a4_candy_notifications", "0005_notification_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationsettings",
            name="email_newsletter",
        ),
    ]
